#### Регистрация нового пользователя

POST http://localhost:3010/api/users/register HTTP/1.1
content-type: application/json

{
    "email": "kukuha@mail.com",
    "password": "15560KukuhaP",
    "firstName": "Томара",
    "lastName": "Кукушкина"
}

#### Авторизация пользователя

POST http://localhost:3010/api/users/login HTTP/1.1
content-type: application/json

{
    "email": "kukuha@mail.com",
    "password": "hjsfbhdjs2"
}

#### Получение информации о зарегистрированном пользователе

GET http://localhost:3010/api/users/65a3f66ac7d55ebb0a1b9b65 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NWVhMjMxMmYzZjZmNTVmMzg4MjQ2YiIsImVtYWlsIjoia3VrdWhhQG1haWwuY29tIiwibGFzdE5hbWUiOiLQmtGD0LrRg9GI0LrQuNC90LAiLCJmaXJzdE5hbWUiOiLQotC-0LzQsNGA0LAiLCJpYXQiOjE3MTkwNDI4MDcsImV4cCI6MTcxOTA4NjAwN30.PhQSDVk-HL8ga8gcVjyQZBvvyJ1geTqjafd01UX63Rk

##### Запрос на обновление пары токенов

POST http://localhost:3010/api/users/refresh HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NWVhMjMxMmYzZjZmNTVmMzg4MjQ2YiIsImVtYWlsIjoia3VrdWhhQG1haWwuY29tIiwibGFzdE5hbWUiOiLQmtGD0LrRg9GI0LrQuNC90LAiLCJmaXJzdE5hbWUiOiLQotC-0LzQsNGA0LAiLCJ0b2tlbklkIjoiODVkMTU4ZjItZmJlNi00NTExLWFkNWYtMjM5ZDUyZWM4MDhmIiwiaWF0IjoxNzE5NDY1MDMxLCJleHAiOjE3MTk4OTcwMzF9.ZOm3FHOzFE3rTwbdPl5-S_qnvJcBSs2u0fplYxnns58


##### Смена пароля пользователя
PATCH http://localhost:3010/api/users/password/change HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NWVhMjMxMmYzZjZmNTVmMzg4MjQ2YiIsImVtYWlsIjoia3VrdWhhQG1haWwuY29tIiwibGFzdE5hbWUiOiLQmtGD0LrRg9GI0LrQuNC90LAiLCJmaXJzdE5hbWUiOiLQotC-0LzQsNGA0LAiLCJ0b2tlbklkIjoiMTIwODVkZWYtYjc2ZC00OTM1LTg0M2QtNTcyM2VlYTVlYjExIiwiaWF0IjoxNzE5MDQyODA3LCJleHAiOjE3MTk0NzQ4MDd9.0hYrzcTm10Ad0taEhxSvZ0Y9boISOIkcaLlRoJRfkMA

{
    "currentPassword": "15560KukuhaP",
    "password": "hjsfbhdjs2"
}

